[package]
name = "rustcutter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
eyre = "0.6.8"
ffmpeg-next = "6.0.0"

[profile.release]
strip = true
opt-level = "z"

